### ISSUE TITLE
Information not displayed

### ISSUE THREAD

**Issue by ahmdfiras** [SCM-MINIPROJECT/MINI-PROJECT#1]
No information on the doctor's tab displayed on client side hardware and software specification

**Comment by fazriiii** [comment]
Work is on progress.. Getting information from the hospital department to proceed @ahmdfiras

**Comment by fazriiii** [comment]
The doctor.html page have successfully updated @SCM-MINIPROJECT/g1  @ahmdfiras @ZulaikhaZuremi @fathiyahhanim @extraAA

**Comment by ahmdfiras** [comment]
Thank you
